services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8076:80"
    depends_on:
      - app
    container_name: blog_nginx
    networks:
      - blog-network

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: blog_app
    environment:
      DB_HOST: db
      DB_DATABASE: blog_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - blog-network

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - blog_db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "8101:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: blog_db
    networks:
      - blog-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    container_name: blog_phpmyadmin
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  blog_db_data:
    driver: local
